CREATE TABLE users (
  id VARCHAR(30) NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  pwd VARCHAR(255) NOT NULL, 
  email VARCHAR(100) NOR NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIME


)